### ISSUE TITLE
bug: Uncaught TypeError: (0 , _reactQuery.QueryClient) is not a constructor

### ISSUE THREAD

**Issue by jellohouse** [wagmi-dev/wagmi#3160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.5

### Current Behavior

Trying to integrate wagmi in my Plasmo chrome extension popup like this:

```javascript
...
import { WagmiConfig, createConfig, mainnet } from 'wagmi'
import { createPublicClient, http } from 'viem'

const wagmiConfig = createConfig({
  autoConnect: true,
  publicClient: createPublicClient({
    chain: mainnet,
    transport: http()
  }),
});

function App(props) {
  return (
    <WagmiConfig config={wagmiConfig}>
      <MemoryRouter>
        <PopupRouter />
      </MemoryRouter>
    </WagmiConfig>
  );
}

export default App;
```

But i get this error:
```
Uncaught TypeError: (0 , _reactQuery.QueryClient) is not a constructor
    at createConfig (index.js:14:21)
    at iodw8.react/jsx-dev-runtime (App.jsx:35:16)
    at newRequire (popup.7d3dc21e.js:72:24)
    at localRequire (popup.7d3dc21e.js:85:35)
    at 1LU0f.react/jsx-dev-runtime (popup.jsx:4:1)
    at newRequire (popup.7d3dc21e.js:72:24)
    at localRequire (popup.7d3dc21e.js:85:35)
    at Vd1oM.react/jsx-dev-runtime (popup.tsx:9:5)
    at newRequire (popup.7d3dc21e.js:72:24)
    at popup.7d3dc21e.js:123:5
```

### Expected Behavior

Wagmi should usually work in a chrome extension popup.

### Steps To Reproduce

1. pnpm create plasmo

2. pnpm i wagmi viem

3. insert this code in popup.js

```javascript
import { WagmiConfig, createConfig, mainnet } from 'wagmi'
import { createPublicClient, http } from 'viem'

const wagmiConfig = createConfig({
  autoConnect: true,
  publicClient: createPublicClient({
    chain: mainnet,
    transport: http()
  }),
});

export default function Popup(props) {
  return (
    <WagmiConfig config={wagmiConfig}>
      <div>Test</div>
    </WagmiConfig>
  )
}

```

4. pnpm dev

5. Load extension in browser -> right click the extension & click "Inspect Popup"

**Comment by Linch1** [comment]
I fixed this by manually importing

`import * as ReactQuery from "@tanstack/react-query"`

in the index.js of my project, didn't understood why this works..

**Comment by jellohouse** [comment]
Hey @Linch1 when i tried to add `import * as ReactQuery from "@tanstack/react-query"` at the top of my App file where i create my wagmi config i got an error: `Cannot find module '@tanstack/react-query'`

So i tried to install it, but then i still get the same error as before `Uncaught TypeError: (0 , _reactQuery.QueryClient) is not a constructor`

Did you have to install @tanstack/react-query separately?

**Comment by Linch1** [comment]
nope, i just imported it  it was installed as a dependency when i installed wagmi

**Comment by tmm** [comment]
Bundler issue

**Comment by jellohouse** [comment]
Thanks @Linch1 I managed to get it working with your solution, but i had to install the exact same version of tanstack/react-query which wagmi was using. Then the `module could not be found` error went away and the other error too :)

But at the end of the day, @tmm you are right that it's a bundler issue - it nothing to do with wagmi really 👍
